// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/classes.proto

package org.fit.sra.protog;

public final class Classes {
  private Classes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SoundEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SoundEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto/classes.proto\022\005proto\"t\n\nSoundEve" +
      "nt\022\n\n\002id\030\001 \001(\t\022#\n\010category\030\002 \001(\0162\021.proto" +
      ".SoundClass\022!\n\010severity\030\003 \001(\0162\017.proto.Se" +
      "verity\022\022\n\nconfidence\030\004 \001(\002*5\n\010Severity\022\n" +
      "\n\006OTHERS\020\000\022\007\n\003LOW\020\001\022\n\n\006MEDIUM\020\002\022\010\n\004HIGH\020" +
      "\003*\223\002\n\nSoundClass\022\013\n\007UNKNOWN\020\000\022\t\n\005SIREN\020\001" +
      "\022\014\n\010CAR_HORN\020\002\022\r\n\tEXPLOSION\020\003\022\023\n\017GUNSHOT" +
      "_HANDGUN\020\004\022\021\n\rGUNSHOT_RIFLE\020\005\022\027\n\023GUNSHOT" +
      "_MACHINE_GUN\020\006\022\r\n\tCAR_CRASH\020\007\022\021\n\rTHUNDER" +
      "_STORM\020\010\022\017\n\013CRYING_BABY\020\t\022\016\n\nFIRE_WORKS\020" +
      "\n\022\014\n\010CHAINSAW\020\013\022\033\n\027EMERGENCY_VEHICLE_SIR" +
      "EN\020\014\022\r\n\tSCREAMING\020\r\022\022\n\016GLASS_BREAKING\020\016B" +
      "\026\n\022org.fit.sra.protogP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_SoundEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_SoundEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SoundEvent_descriptor,
        new java.lang.String[] { "Id", "Category", "Severity", "Confidence", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
