// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/classes.proto

package org.fit.sra.protog;

public interface SoundEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.SoundEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.proto.SoundClass category = 2;</code>
   * @return The enum numeric value on the wire for category.
   */
  int getCategoryValue();
  /**
   * <code>.proto.SoundClass category = 2;</code>
   * @return The category.
   */
  org.fit.sra.protog.SoundClass getCategory();

  /**
   * <code>.proto.Severity severity = 3;</code>
   * @return The enum numeric value on the wire for severity.
   */
  int getSeverityValue();
  /**
   * <code>.proto.Severity severity = 3;</code>
   * @return The severity.
   */
  org.fit.sra.protog.Severity getSeverity();

  /**
   * <code>float confidence = 4;</code>
   * @return The confidence.
   */
  float getConfidence();
}
