// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/classes.proto

package org.fit.sra.protog;

/**
 * Protobuf enum {@code proto.SoundClass}
 */
public enum SoundClass
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN = 0;</code>
   */
  UNKNOWN(0),
  /**
   * <code>SIREN = 1;</code>
   */
  SIREN(1),
  /**
   * <code>CAR_HORN = 2;</code>
   */
  CAR_HORN(2),
  /**
   * <code>EXPLOSION = 3;</code>
   */
  EXPLOSION(3),
  /**
   * <code>GUNSHOT_HANDGUN = 4;</code>
   */
  GUNSHOT_HANDGUN(4),
  /**
   * <code>GUNSHOT_RIFLE = 5;</code>
   */
  GUNSHOT_RIFLE(5),
  /**
   * <code>GUNSHOT_MACHINE_GUN = 6;</code>
   */
  GUNSHOT_MACHINE_GUN(6),
  /**
   * <code>CAR_CRASH = 7;</code>
   */
  CAR_CRASH(7),
  /**
   * <code>THUNDER_STORM = 8;</code>
   */
  THUNDER_STORM(8),
  /**
   * <code>CRYING_BABY = 9;</code>
   */
  CRYING_BABY(9),
  /**
   * <code>FIRE_WORKS = 10;</code>
   */
  FIRE_WORKS(10),
  /**
   * <code>CHAINSAW = 11;</code>
   */
  CHAINSAW(11),
  /**
   * <code>EMERGENCY_VEHICLE_SIREN = 12;</code>
   */
  EMERGENCY_VEHICLE_SIREN(12),
  /**
   * <code>SCREAMING = 13;</code>
   */
  SCREAMING(13),
  /**
   * <code>GLASS_BREAKING = 14;</code>
   */
  GLASS_BREAKING(14),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN = 0;</code>
   */
  public static final int UNKNOWN_VALUE = 0;
  /**
   * <code>SIREN = 1;</code>
   */
  public static final int SIREN_VALUE = 1;
  /**
   * <code>CAR_HORN = 2;</code>
   */
  public static final int CAR_HORN_VALUE = 2;
  /**
   * <code>EXPLOSION = 3;</code>
   */
  public static final int EXPLOSION_VALUE = 3;
  /**
   * <code>GUNSHOT_HANDGUN = 4;</code>
   */
  public static final int GUNSHOT_HANDGUN_VALUE = 4;
  /**
   * <code>GUNSHOT_RIFLE = 5;</code>
   */
  public static final int GUNSHOT_RIFLE_VALUE = 5;
  /**
   * <code>GUNSHOT_MACHINE_GUN = 6;</code>
   */
  public static final int GUNSHOT_MACHINE_GUN_VALUE = 6;
  /**
   * <code>CAR_CRASH = 7;</code>
   */
  public static final int CAR_CRASH_VALUE = 7;
  /**
   * <code>THUNDER_STORM = 8;</code>
   */
  public static final int THUNDER_STORM_VALUE = 8;
  /**
   * <code>CRYING_BABY = 9;</code>
   */
  public static final int CRYING_BABY_VALUE = 9;
  /**
   * <code>FIRE_WORKS = 10;</code>
   */
  public static final int FIRE_WORKS_VALUE = 10;
  /**
   * <code>CHAINSAW = 11;</code>
   */
  public static final int CHAINSAW_VALUE = 11;
  /**
   * <code>EMERGENCY_VEHICLE_SIREN = 12;</code>
   */
  public static final int EMERGENCY_VEHICLE_SIREN_VALUE = 12;
  /**
   * <code>SCREAMING = 13;</code>
   */
  public static final int SCREAMING_VALUE = 13;
  /**
   * <code>GLASS_BREAKING = 14;</code>
   */
  public static final int GLASS_BREAKING_VALUE = 14;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SoundClass valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SoundClass forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN;
      case 1: return SIREN;
      case 2: return CAR_HORN;
      case 3: return EXPLOSION;
      case 4: return GUNSHOT_HANDGUN;
      case 5: return GUNSHOT_RIFLE;
      case 6: return GUNSHOT_MACHINE_GUN;
      case 7: return CAR_CRASH;
      case 8: return THUNDER_STORM;
      case 9: return CRYING_BABY;
      case 10: return FIRE_WORKS;
      case 11: return CHAINSAW;
      case 12: return EMERGENCY_VEHICLE_SIREN;
      case 13: return SCREAMING;
      case 14: return GLASS_BREAKING;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SoundClass>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SoundClass> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SoundClass>() {
          public SoundClass findValueByNumber(int number) {
            return SoundClass.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.fit.sra.protog.Classes.getDescriptor().getEnumTypes().get(1);
  }

  private static final SoundClass[] VALUES = values();

  public static SoundClass valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SoundClass(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:proto.SoundClass)
}

